import { defineConfig } from 'vite';
import marko from '@marko/run/vite';
import staticAdapter from '@marko/run-adapter-static';
import { markdownContentPlugin } from 'markopress/build';
import { readFileSync } from 'node:fs';

// Load static URLs generated by markopress build
let staticUrls = ['/'];
try {
  staticUrls = JSON.parse(readFileSync('src/.generated/static-urls.json', 'utf-8'));
} catch {
  // File not yet generated on first run
}

export default defineConfig({
  base: process.env.BASE_URL || '/',
  plugins: [
    marko({
      adapter: staticAdapter({
        urls: staticUrls,
      }),
    }),
    markdownContentPlugin(),
  ],
  resolve: {
    // Preserve symlinks for pnpm workspace compatibility
    // This allows Marko to properly discover tags from symlinked packages
    preserveSymlinks: true,
  },
  build: {
    outDir: 'dist',
  },
});
