/**
 * Test plugin to verify enhanced plugin system functionality
 * This plugin exercises all the new hooks in the plugin lifecycle
 */
export const testPlugin = {
    name: '@markopress/test-plugin',
    // Test loadContent hook - load custom content from external source
    async loadContent() {
        console.log('  [test-plugin] loadContent hook called');
        // Simulate loading external content
        return {
            pages: [
                {
                    id: 'plugin-page-1',
                    filePath: '/mock/test-page.md',
                    relativePath: 'test-page.md',
                    type: 'page',
                    urlPath: '/test-page',
                    processed: {
                        frontmatter: {
                            title: 'Plugin-Generated Page',
                            description: 'This page was generated by a plugin'
                        },
                        content: '# Plugin-Generated Page\n\nThis page was generated by a plugin.',
                        html: '<h1>Plugin-Generated Page</h1><p>This page was generated by a plugin.</p>',
                        headers: []
                    }
                }
            ]
        };
    },
    // Test contentLoaded hook - process plugin's own content
    async contentLoaded(ctx) {
        console.log('  [test-plugin] contentLoaded hook called');
        console.log(`    - Plugin has ${ctx.content.pages?.length || 0} pages`);
        console.log(`    - All content has ${ctx.allContent.getPages().length} total pages`);
        // Add a custom route via actions
        ctx.actions.addRoute({
            path: '/plugin-route',
            component: 'test-component.marko',
            meta: {
                generatedBy: 'test-plugin',
                timestamp: Date.now()
            }
        });
        // Add custom data via actions
        ctx.actions.addData('pluginData', {
            message: 'Hello from test plugin',
            version: '1.0.0'
        });
        console.log('    - Added custom route and data');
    },
    // Test allContentLoaded hook - access all content after all plugins
    async allContentLoaded(ctx) {
        console.log('  [test-plugin] allContentLoaded hook called');
        console.log(`    - Total pages: ${ctx.allContent.getPages().length}`);
        console.log(`    - Total docs: ${ctx.allContent.getDocs().length}`);
        console.log(`    - Total blog posts: ${ctx.allContent.getPosts().length}`);
        console.log(`    - Total routes: ${Object.keys(ctx.routes).length}`);
        // Get custom data we added earlier
        const pluginData = ctx.actions.getData();
        console.log(`    - Plugin data keys: ${Array.from(pluginData.keys()).join(', ')}`);
    },
    // Test postBuild hook - perform post-build operations
    async postBuild(ctx) {
        console.log('  [test-plugin] postBuild hook called');
        console.log(`    - Output directory: ${ctx.outDir}`);
        console.log(`    - Total routes: ${Object.keys(ctx.routes).length}`);
        console.log(`    - Total assets: ${ctx.assets.length}`);
        // Log all assets
        ctx.assets.forEach(asset => {
            console.log(`      - ${asset}`);
        });
    },
    // Test extendMarkdown hook - extend markdown parser
    async extendMarkdown(md) {
        console.log('  [test-plugin] extendMarkdown hook called');
        // Add a custom markdown renderer
        md.renderer.rules.custom_block = (tokens, idx) => {
            return `<div class="custom-block">${tokens[idx].content}</div>`;
        };
    },
    // Test extendRoutes hook - modify route manifest
    async extendRoutes(routes) {
        console.log('  [test-plugin] extendRoutes hook called');
        console.log(`    - Modifying ${Object.keys(routes).length} routes`);
        // Add metadata to all routes
        for (const [path, route] of Object.entries(routes)) {
            route.meta = {
                ...route.meta,
                processedBy: 'test-plugin',
                processedAt: new Date().toISOString()
            };
        }
        return routes;
    }
};
export default testPlugin;
